### PR TITLE
Do not attempt to delete protected branches

### LINKED ISSUE #19: Do not attempt deleting protected branches
Currently the action skips deleting the default branch for a repository. However, with GitHub protected branches functionality, multiple branches could be protected and not allowed to be deleted.

If they are protected, the action would attempt deleting them and would fail. Could we instead get a list of all protected branches and not attempt to delete them?

### PR DESCRIPTION
**Pull request by mrwacky42**
Protect the protected.

Fixes #19.

### CODE REVIEW

**Review by GabeL7r — APPROVED** [review]

**Comment by mrwacky42** [comment]
@jessfraz - Your Docker registry is bah-roken ;(

**Comment by mrwacky42** [comment]
Hi there.

**Comment by jessfraz** [comment]
thanks!

**Comment by mrwacky42** [comment]
Fixes #18

**Pull request merged**
